Repository JIOK-s/Purchase, pull requests merged in 2023-04, with the labels that each got.

#9 full request 요청
  README.md
  src/main/java/com/jiok/purchase/domain/Hello.java
  src/main/java/com/jiok/purchase/domain/members/Members.java
  src/main/java/com/jiok/purchase/domain/originProduct/OriginProduct.java
  src/main/java/com/jiok/purchase/domain/userProduct/CarProduct.java
  src/main/java/com/jiok/purchase/domain/userProduct/GeneralProduct.java
  src/main/java/com/jiok/purchase/domain/userProduct/UserProduct.java
  src/main/java/com/jiok/purchase/entity/CarProduct.java
  src/main/java/com/jiok/purchase/entity/GeneralProduct.java
  src/test/java/com/jiok/purchase/PurchaseApplicationTests.java
  src/test/java/com/jiok/purchase/domain/userProduct/CarProductTest.java
Labels: bug

#10 [feat] 견적, 방문평가 entity 생성 및 테스트
  src/main/java/com/jiok/purchase/domain/quotation/Funnel.java
  src/main/java/com/jiok/purchase/domain/quotation/Quotation.java
  src/main/java/com/jiok/purchase/domain/quotation/QutProcStCd.java
  src/main/java/com/jiok/purchase/domain/visitEstimate/VisitEstimate.java
  src/main/java/com/jiok/purchase/domain/visitEstimate/VisitEstmProcStCd.java
  src/test/java/com/jiok/purchase/PurchaseApplicationTests.java
  src/test/java/com/jiok/purchase/domain/quotation/QuotationTest.java
  src/test/java/com/jiok/purchase/domain/userProduct/CarProductTest.java
Labels: enhancement

#13 [feat] readme 수정
  README.md
  img/work_flow.png
  readmeDir/meetingLog/README.md
Labels: documentation

#15 [feat] 04-11 업무일지 작성
  README.md
  readmeDir/meetingLog/README.md
Labels: documentation

#16 [fix] 1. jpa 설정(application.yml) 수정 - ddl-auto 설정 변경 및 show-sql 설정 변경…
  src/main/resources/application.yml
  src/test/java/com/jiok/purchase/domain/quotation/QuotationTest.java
  src/test/java/com/jiok/purchase/domain/userProduct/CarProductTest.java
Labels: enhancement

#17 [feat] 04-15 업무일지 작성
  readmeDir/meetingLog/README.md
Labels: documentation

#18 [feat] index 파일 생성
  src/main/resources/static/index.html
Labels: enhancement

#20 [feat] travis ci yml 설정
  .travis.yml
Labels: enhancement

#21 [feat] 업무일지, 발생 문제 및 해결 작성
  README.md
  readmeDir/meetingLog/README.md
Labels: documentation

#23 [fix] travis s3 연동 - develop branch permission on
  .travis.yml
Labels: enhancement

#32 [docs] 업무일지, 발생 문제 및 해결 작성
  README.md
  readmeDir/meetingLog/README.md
Labels: documentation
