Repository JIOK-s/Purchase, pull requests merged in 2023-05, with the labels that each got.

#33 [feat] 매입 모듈 application.yml db분리 및 서버 디렉토리 위치 변경
  .gitignore
  appspec.yml
  src/main/resources/application.yml
Labels: enhancement

#34 [feat] deploy.sh 작성
  script/deploy.sh
Labels: enhancement

#35 [feat] 자동 빌드 배포를 위한 travis, appspec, deploy 설정
  .travis.yml
  appspec.yml
  script/deploy.sh
Labels: enhancement

#36 [fix] deploy package 위치 변경
  scripts/deploy.sh
Labels: enhancement

#37 [fix] deploy.sh에서 jar 파일 경로 수정
  scripts/deploy.sh
Labels: enhancement

#38 [docs] 업무일지 작성
  readmeDir/meetingLog/README.md
Labels: documentation

#39 [feat] deploy pid 찾기 수정 및 appspec mod 권한 부여
  appspec.yml
  scripts/deploy.sh
Labels: enhancement

#40 [fix] deploy.sh chmod 권한 수정
  appspec.yml
Labels: enhancement

#41 [test] deploy 테스트
  src/main/resources/static/index.html
Labels: enhancement

#42 [feat] codedeploy시 nohup 사용에 대한 지속적인 대기에 대한 부분 수정
  scripts/deploy.sh
  src/main/resources/static/index.html
Labels: enhancement

#46 [feat] 시세 class 추가 및 그에 따른 연관관계들 수정 및 테스트 코드 수정
  src/main/java/com/jiok/purchase/domain/marketPrice/MarketPrice.java
  src/main/java/com/jiok/purchase/domain/members/Members.java
  src/main/java/com/jiok/purchase/domain/originProduct/OriginProduct.java
  src/main/java/com/jiok/purchase/domain/quotation/Quotation.java
  src/main/java/com/jiok/purchase/domain/userProduct/CarProduct.java
  src/main/java/com/jiok/purchase/domain/userProduct/GeneralProduct.java
  src/main/java/com/jiok/purchase/domain/userProduct/UserProduct.java
  src/test/java/com/jiok/purchase/domain/quotation/QuotationTest.java
  src/test/java/com/jiok/purchase/domain/userProduct/CarProductTest.java
  src/test/resources/application.yml
Labels: enhancement, test

#47 [feat] estimator class 생성 및 visitEstimate test 수정
  src/main/java/com/jiok/purchase/domain/estimator/Estimator.java
  src/main/java/com/jiok/purchase/domain/estimator/EstmrLoc.java
  src/main/java/com/jiok/purchase/domain/visitEstimate/VisitEstimate.java
  src/test/java/com/jiok/purchase/domain/visitEstimate/VisitEstimateTest.java
Labels: enhancement, test

#48 [docs] 2023-05-05 업무일지 작성 및 알게 된 점 추가
  README.md
  readmeDir/meetingLog/README.md
Labels: documentation

#51 [feat] 계약 entity 생성 및 테스트
  src/main/java/com/jiok/purchase/domain/contract/Contract.java
  src/main/java/com/jiok/purchase/domain/contract/NmDivdCd.java
  src/main/java/com/jiok/purchase/domain/quotation/Quotation.java
  src/test/java/com/jiok/purchase/domain/contract/ContractTest.java
Labels: enhancement

#52 [feat] 배송 entity 생성 및 테스트
  src/main/java/com/jiok/purchase/domain/contract/Contract.java
  src/main/java/com/jiok/purchase/domain/delivery/Delivery.java
  src/main/java/com/jiok/purchase/domain/delivery/DlvProcStCd.java
  src/main/java/com/jiok/purchase/domain/quotation/Quotation.java
  src/main/java/com/jiok/purchase/domain/visitEstimate/VisitEstimate.java
  src/test/java/com/jiok/purchase/domain/delivery/DeliveryTest.java
Labels: enhancement

#55 [feat] 회원, 평가사, 시세 엔티티 테스트 코드 작성
  src/test/java/com/jiok/purchase/domain/contract/ContractTest.java
  src/test/java/com/jiok/purchase/domain/estimator/EstimatorTest.java
  src/test/java/com/jiok/purchase/domain/marketPrice/MarketPriceTest.java
  src/test/java/com/jiok/purchase/domain/members/MembersTest.java
Labels: test

#56 [test] 원상품, 일반상품 엔티티 테스트 코드 작성
  src/main/java/com/jiok/purchase/domain/userProduct/GeneralProduct.java
  src/test/java/com/jiok/purchase/domain/originProduct/OriginProductTest.java
  src/test/java/com/jiok/purchase/domain/userProduct/GeneralProductTest.java
Labels: test

#57 [docs] 2023-05-13 일지 작성
  readmeDir/meetingLog/README.md
Labels: documentation

#59 [feat] jacoco 설치 및 테스트 커버리지 80에 맞춰 테스트 코드들 수정
  README.md
  build.gradle
  lombok.config
  src/main/java/com/jiok/purchase/service/HelloService.java
  src/main/java/com/jiok/purchase/web/controller/HelloController.java
  src/test/java/com/jiok/purchase/PurchaseApplicationTests.java
  src/test/java/com/jiok/purchase/domain/contract/ContractTest.java
  src/test/java/com/jiok/purchase/domain/delivery/DeliveryTest.java
  src/test/java/com/jiok/purchase/domain/estimator/EstimatorTest.java
  src/test/java/com/jiok/purchase/domain/quotation/QuotationTest.java
  src/test/java/com/jiok/purchase/domain/visitEstimate/VisitEstimateTest.java
Labels: enhancement

#60 [docs] 코드 작성 플로우 추가 및 업무일지 작성
  README.md
  img/purchase-test-coverage.png
  readmeDir/meetingLog/README.md
Labels: documentation

#63 [docs] 업무일지 작성
  readmeDir/meetingLog/README.md
Labels: documentation
